### ISSUE TITLE
FileLoadException

### ISSUE THREAD

**Issue by johnweidauer** [Inteligenz/X12Parser#15]
System.IO.FileLoadException: 'Could not load file or assembly 'OopFactory.X12, Version=2.1.7.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'

This happens after changing to 64bit, any assistance would be appreciated

**Comment by nwlynch** [comment]
Have you had any luck resolving this?

**Comment by johnweidauer** [comment]
Yes I did.  I had to create a new project and it began working.  My issue I believe is because our original project was made in Visual Studio 2012 with 32 bit processor preferred, with an older version of the X12 Parser; downloading the most recent version of X12 Parser with a new Visual Studio 2019 64 bit project worked without issue.
