### ISSUE TITLE
Error Parsing Certain 837 Claims

### ISSUE THREAD

**Issue by larryrshirley** [Inteligenz/X12Parser#22]
This error appears to occur for some 837 institutional claims. The CAS segment noted in the error appears to be formatted correctly. 

An exception of type 'OopFactory.X12.Parsing.Model.TransactionValidationException' occurred in OopFactory.X12.dll but was not handled in user code
Segment 'CAS*OA*23*179.88' in segment position 99 within transaction '000000023' cannot be identified within the supplied specification for transaction set 837 in any of the expected loops: 2000A[1],2000B[2],2300,2400.  To change this to a warning, pass throwExceptionOnSyntaxErrors = false to the X12Parser constructor.

**Comment by larryrshirley** [comment]
There is an asterisk between CAS and OA in the exception string above. For some reason, it is being removed in the comment.

**Comment by bobthebeef** [comment]
@larryrshirley we have run into this as well. Was there a solution or root cause that you found?
